import React from "react";

function Board() {
    return (
        <>
            <div id="11" class="square"></div>
            <div id="12" class="square"></div>
            <div id="13" class="square"></div>
            <div id="14" class="square"></div>
            <div id="15" class="square"></div>
            <div id="16" class="square"></div>
            <div id="17" class="square"></div>
            <div id="18" class="square"></div>
            <div style="clear: both;"></div>
            <div id="21" class="square"></div>
            <div id="22" class="square"></div>
            <div id="23" class="square"></div>
            <div id="24" class="square"></div>
            <div id="25" class="square"></div>
            <div id="26" class="square"></div>
            <div id="27" class="square"></div>
            <div id="28" class="square"></div>
            <div style="clear: both;"></div>
            <div id="31" class="square"></div>
            <div id="32" class="square"></div>
            <div id="33" class="square"></div>
            <div id="34" class="square"></div>
            <div id="35" class="square"></div>
            <div id="36" class="square"></div>
            <div id="37" class="square"></div>
            <div id="38" class="square"></div>
            <div style="clear: both;"></div>
            <div id="41" class="square"></div>
            <div id="42" class="square"></div>
            <div id="43" class="square"></div>
            <div id="44" class="square"></div>
            <div id="45" class="square"></div>
            <div id="46" class="square"></div>
            <div id="47" class="square"></div>
            <div id="48" class="square"></div>
            <div style="clear: both;"></div>
            <div id="51" class="square"></div>
            <div id="52" class="square"></div>
            <div id="53" class="square"></div>
            <div id="54" class="square"></div>
            <div id="55" class="square"></div>
            <div id="56" class="square"></div>
            <div id="57" class="square"></div>
            <div id="58" class="square"></div>
            <div style="clear: both;"></div>
            <div id="61" class="square"></div>
            <div id="62" class="square"></div>
            <div id="63" class="square"></div>
            <div id="64" class="square"></div>
            <div id="65" class="square"></div>
            <div id="66" class="square"></div>
            <div id="67" class="square"></div>
            <div id="68" class="square"></div>
            <div style="clear: both;"></div>
            <div id="71" class="square"></div>
            <div id="72" class="square"></div>
            <div id="73" class="square"></div>
            <div id="74" class="square"></div>
            <div id="75" class="square"></div>
            <div id="76" class="square"></div>
            <div id="77" class="square"></div>
            <div id="78" class="square"></div>
            <div style="clear: both;"></div>
            <div id="81" class="square"></div>
            <div id="82" class="square"></div>
            <div id="83" class="square"></div>
            <div id="84" class="square"></div>
            <div id="85" class="square"></div>
            <div id="86" class="square"></div>
            <div id="87" class="square"></div>
            <div id="88" class="square"></div>
            <div style="clear: both;"></div>
        </>
    );
  }